### ISSUE TITLE
Spinner - weird behaviour

### ISSUE THREAD

**Issue by AnthonyAkentiev** [Thetta/DAO-FrontendBase#10]
1) sometimes spinner is moving all the time, but the data is not loaded
2) sometimes data is not loaded at all:

<img width="374" alt="screen shot 2018-10-26 at 08 53 07" src="https://user-images.githubusercontent.com/1623033/47549541-ae27c400-d8fc-11e8-9e56-8f8b3e4eee91.png">

**Comment by ryzhak** [comment]
Can not reproduce. Reloaded 10 times in Chrome and all 10 times prices were loaded. There is also an error message "Error on updating prices" in case something went wrong. If you encounter this issue again then console output would be useful.
